spring:
  application:
    name: shoapp
  datasource:
    url: jdbc:mysql://localhost:3306/shoapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
        
server:
  port: 8084

api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: Jwi+cjscdAFS1YFgn2Yb02mHd1AAzQioRwK+sGWYnNY=